version: '3.4'

services:
  backendtest:
    image: backendtest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 3000:3000

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5422:5432
    volumes:
      #   # - './var/lib/postgresql/data'
      - 'backendtest-db:/var/lib/postgresql/data'
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - '6379:6379'

volumes:
  backendtest-db:
